# Generated by Django 5.2 on 2025-04-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=1.0),
        ),
    ]
